repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.3
    hooks:
      - id: ruff
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]
      
      - id: ruff-format
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [
          "types-requests", 
          "python-dotenv",
          "haystack-ai",
          "qdrant-haystack",
          "streamlit",
        ]
        